# This file was generated by GoReleaser. DO NOT EDIT.
cask "opentaint" do
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/seqra/opentaint/releases/download/v#{version}/opentaint-full_darwin_amd64.tar.gz"
      sha256 "243dc46d65ae15ae06ecfaa045196af82bd41ba17b4847913307f520aaad0125"
    end
    on_arm do
      url "https://github.com/seqra/opentaint/releases/download/v#{version}/opentaint-full_darwin_arm64.tar.gz"
      sha256 "b645623985af356eda5c3453f57df4e3afa1f97050764e562e1f8251d43e412d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/seqra/opentaint/releases/download/v#{version}/opentaint-full_linux_amd64.tar.gz"
      sha256 "f45f23db1dd407158c10daf7065b264805d720a59e6b63004dcfab0bd5cd27ce"
    end
    on_arm do
      url "https://github.com/seqra/opentaint/releases/download/v#{version}/opentaint-full_linux_arm64.tar.gz"
      sha256 "53d09c2305f5296ab89fe39fd1cc75217c1b7575f71c440b6236a109f189311e"
    end
  end

  name "opentaint"
  desc "The open source taint analysis engine"
  homepage "https://github.com/seqra/opentaint"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "opentaint"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/opentaint"]
  end

  # No zap stanza required

end
