# This file was generated by GoReleaser. DO NOT EDIT.
cask "opentaint" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "39d17431589ae586c66af10e5c4afaff1cf280ddbe70870f09f3866675503fbc"
      url "https://github.com/seqra/opentaint/releases/download/v#{version}/opentaint-full_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "769f1d7fb71e3a36b2d6136f778f038e5e8ba4000d1b6a64d5ffed6fe0445102"
      url "https://github.com/seqra/opentaint/releases/download/v#{version}/opentaint-full_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2e3d81e4332116f56b58ffaa171d99a5c88e79d2e361c783b893b3a9903e422b"
      url "https://github.com/seqra/opentaint/releases/download/v#{version}/opentaint-full_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4a2d33f00dd7fbecacee9b122823c1f71777dd4c14bfc1743453597ae3407c88"
      url "https://github.com/seqra/opentaint/releases/download/v#{version}/opentaint-full_linux_arm64.tar.gz"
    end
  end

  name "opentaint"
  desc "The open source taint analysis engine"
  homepage "https://github.com/seqra/opentaint"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "opentaint"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/opentaint"]
  end

  # No zap stanza required

end
