# This file was generated by GoReleaser. DO NOT EDIT.
cask "opentaint" do
  version "0.4.3"

  on_macos do
    on_intel do
      sha256 "3707bcf7b0d46ba014a3ddbd4415b0af943b46b7ace89e0a534037ab33a3c24a"
      url "https://github.com/seqra/opentaint/releases/download/v#{version}/opentaint-full_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "66bff1f0fbe51608052b484b0e56694ede45a4ac1c80aac10f981f8a6e3444cf"
      url "https://github.com/seqra/opentaint/releases/download/v#{version}/opentaint-full_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1fe274d91a234894d29b97983de86cc76ca8f35fb1f6f86423ee55c3eef66c93"
      url "https://github.com/seqra/opentaint/releases/download/v#{version}/opentaint-full_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "acef942aaf1815a91098bd48f402ae8dc145e5a2cc43d0fcbacc802456ef8aca"
      url "https://github.com/seqra/opentaint/releases/download/v#{version}/opentaint-full_linux_arm64.tar.gz"
    end
  end

  name "opentaint"
  desc "The open source taint analysis engine"
  homepage "https://github.com/seqra/opentaint"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "opentaint"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/opentaint"]
  end

  # No zap stanza required

end
