# This file was generated by GoReleaser. DO NOT EDIT.
cask "seqra" do
  name "seqra"
  desc "Security-focused static analyzer for Java and Kotlin web applications"
  homepage "https://github.com/seqra/seqra"
  version "2.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "seqra"

  on_macos do
    on_intel do
      url "https://github.com/seqra/seqra/releases/download/v#{version}/seqra-full_darwin_amd64.tar.gz"
      sha256 "364fc8dd51e5049de2f99b115479de6e5376bfb49a52991c1dd50776831fdf3f"
    end
    on_arm do
      url "https://github.com/seqra/seqra/releases/download/v#{version}/seqra-full_darwin_arm64.tar.gz"
      sha256 "dd1aaf7daac2711e1e6842daf93ce41008c6c3afc24cadff3b55fb702d5bd202"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/seqra/seqra/releases/download/v#{version}/seqra-full_linux_amd64.tar.gz"
      sha256 "04a3ec668fac9ed381e99a166dfa5234da0a5c0908b8b8565a2f9d2bb3008bd7"
    end
    on_arm do
      url "https://github.com/seqra/seqra/releases/download/v#{version}/seqra-full_linux_arm64.tar.gz"
      sha256 "349d1e341f8f45af54f67d0745ba52b3b953cf142cb4b292b632d0103431efb7"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/seqra"]
  end

  # No zap stanza required
end
