# This file was generated by GoReleaser. DO NOT EDIT.
cask "seqra" do
  name "seqra"
  desc "Security-focused static analyzer for Java and Kotlin web applications"
  homepage "https://github.com/seqra/seqra"
  version "2.6.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "seqra"

  on_macos do
    on_intel do
      url "https://github.com/seqra/seqra/releases/download/v#{version}/seqra-full_darwin_amd64.tar.gz"
      sha256 "9ae9da0ca12e0a4b3160b2d689d7e01a6d43811fd859ec9c42a1b76a126d2872"
    end
    on_arm do
      url "https://github.com/seqra/seqra/releases/download/v#{version}/seqra-full_darwin_arm64.tar.gz"
      sha256 "5ad36b166e14bae978483b1e447a044ebc0a910fe12df2b282969cec140bf761"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/seqra/seqra/releases/download/v#{version}/seqra-full_linux_amd64.tar.gz"
      sha256 "34f1aaf00386a99023917014d1429670a217c3c2cd3543693c88755740d4b73e"
    end
    on_arm do
      url "https://github.com/seqra/seqra/releases/download/v#{version}/seqra-full_linux_arm64.tar.gz"
      sha256 "37c1688251dca64f22b40d32b43a25a5157a3b6843353814878dad9dadeddae1"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/seqra"]
  end

  # No zap stanza required
end
