# This file was generated by GoReleaser. DO NOT EDIT.
cask "seqra" do
  name "seqra"
  desc "Security-focused static analyzer for Java and Kotlin web applications"
  homepage "https://github.com/seqra/seqra"
  version "2.6.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "seqra"

  on_macos do
    on_intel do
      url "https://github.com/seqra/seqra/releases/download/v#{version}/seqra-full_darwin_amd64.tar.gz"
      sha256 "11b4d720aa27ffb72eae9f47dc67336f9f01b026ca985364c1d3975e34d68d78"
    end
    on_arm do
      url "https://github.com/seqra/seqra/releases/download/v#{version}/seqra-full_darwin_arm64.tar.gz"
      sha256 "d83e0d1d1a64ff3eeec582a29534cae79ed4dd929addfc1b17c4c64f81d3a8c3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/seqra/seqra/releases/download/v#{version}/seqra-full_linux_amd64.tar.gz"
      sha256 "3c6e38ab76c7092f4fde917c825fe255117b2540f1ea255e90a6cc2b984e7b44"
    end
    on_arm do
      url "https://github.com/seqra/seqra/releases/download/v#{version}/seqra-full_linux_arm64.tar.gz"
      sha256 "75e4824b0522e727f9c60a606a0cbabd4b2c9c033ad58898006faa53e8d63ab1"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/seqra"]
  end

  # No zap stanza required
end
